name: PytonFunctionsCI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Zip Folder
        run: zip -r release.zip ../../dagger-py-functions
      - name: Release to Github
        run: echo "Release"