name: PytonFunctionsCI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Release to Github
        run: echo $GITHUB_WORKSPACE
      - name: Zip Folder
        working-directory: ./dagger
        run: zip -r dagger-py-functions.zip $GITHUB_WORKSPACE/dagger-py-functions