name: py-package
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Zip dagger-py-functions
        run: zip -r dagger-py-functions.zip $GITHUB_WORKSPACE/dagger-py-functions
      - name: Show Files
        run: ls -a
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dagger-py-functions.zip"
          token: ${{ secrets.GITHUB_TOKEN }}